pipeline {
  agent {
    docker {
      image 'node:20-alpine'
      args '-u root:root'
    }
  }

  options { timestamps() }

  environment {
    CI = "true"
    HEROKU_APP = "pipeline-as-code"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Install') {
      steps {
        dir('pipeline-as-code') {
          sh 'npm ci'
        }
      }
    }

    stage('Lint') {
      steps {
        dir('pipeline-as-code') {
          sh 'npm run lint'
        }
      }
    }

    stage('Build') {
      steps {
        dir('pipeline-as-code') {
          sh 'npm run build'
        }
      }
    }

    stage('Deploy Heroku') {
      steps {
        withCredentials([string(credentialsId: 'HEROKU_API_KEY', variable: 'HEROKU_TOKEN')]) {
          sh '''
            set -e
            git remote remove heroku || true
            git remote add heroku https://heroku:$HEROKU_TOKEN@git.heroku.com/$HEROKU_APP.git
            git push heroku HEAD:main --force
          '''
        }
      }
    }
  }

  post {
    always { echo "Pipeline finished." }
  }
}